# nightfox
[[colors.indexed_colors]]
color = "0xf4a261"
index = 16

[[colors.indexed_colors]]
color = "0xd67ad2"
index = 17

[colors.bright]
black = "0x475072"
blue = "0x84cee4"
cyan = "0x59f0ff"
green = "0x58cd8b"
magenta = "0xb8a1e3"
red = "0xd6616b"
white = "0xf2f2f2"
yellow = "0xffe37e"

[colors.normal]
black = "0x393b44"
blue = "0x719cd6"
cyan = "0x63cdcf"
green = "0x81b29a"
magenta = "0x9d79d6"
red = "0xc94f6d"
white = "0xdfdfe0"
yellow = "0xdbc074"

[colors.primary]
background = "0x192330"
foreground = "0xcdcecf"

[font]
builtin_box_drawing = true
size = 10.5

[font.normal]
family = "CaskaydiaCove NF"

[window]
dynamic_title = true

[window.dimensions]
columns = 120
lines = 35

[window.padding]
x = 3
y = 3
