[".local/share/zellij/plugins/vim-zellij-navigator.wasm"]
type = "file"
url = "https://github.com/hiasr/vim-zellij-navigator/releases/download/0.3.0/vim-zellij-navigator.wasm"

[".local/share/zellij/plugins/zjstatus.wasm"]
type = "file"
url = "https://github.com/dj95/zjstatus/releases/download/v0.25.0/zjstatus.wasm"
