misc {
    on_focus_under_fullscreen = 1
    exit_window_retains_fullscreen = true
    enable_swallow = false
    swallow_regex = ^(kitty)$
    swallow_exception_regex = (kitty|dragon)
}

binds {
    workspace_center_on = 1
    movefocus_cycles_fullscreen = true
}
# vim: ft=hyprlang
