[debian]
image="docker.io/library/debian:stable"
init=true
entry=false

additional_packages="bat curl debianutils direnv eza fd-find fzf git htop lazygit openssh-client procps ripgrep shellcheck starship wl-clipboard zip zsh zsh-autosuggestions zsh-syntax-highlighting"
additional_packages="systemd libpam-systemd"

init_hooks=[ -f /root/.first_run ] || wcurl https://github.com/neovim/neovim/releases/download/v0.12.2/nvim-linux-x86_64.appimage && chmod +x nvim-linux-x86_64.appimage;
init_hooks=[ -f /root/.first_run ] || ./nvim-linux-x86_64.appimage --appimage-extract && rm nvim-linux-x86_64.appimage;
init_hooks=[ -f /root/.first_run ] || cp -a squashfs-root/* / && rm -fr squashfs-root;

init_hooks=[ -f /root/.first_run ] || echo alias bat="batcat" >> /distrobox.zsh;
init_hooks=[ -f /root/.first_run ] || echo alias cat="batcat --style=plain" >> /distrobox.zsh;
init_hooks=[ -f /root/.first_run ] || echo alias fd="fdfind" >> /distrobox.zsh;
init_hooks=[ -f /root/.first_run ] || echo alias grep="command grep --color=auto" >> /distrobox.zsh;
init_hooks=[ -f /root/.first_run ] || echo alias ip="command ip --color=auto" >> /distrobox.zsh;
init_hooks=[ -f /root/.first_run ] || echo alias ls="eza --color=auto --group-directories-first -F" >> /distrobox.zsh;
init_hooks=[ -f /root/.first_run ] || echo alias l="ls --smart-group -lgahM" >> /distrobox.zsh;
init_hooks=[ -f /root/.first_run ] || echo alias lzg="lazygit" >> /distrobox.zsh;
init_hooks=[ -f /root/.first_run ] || echo "sudo setsid -f apt update -qqy &>/dev/null" >> /distrobox.zsh;

init_hooks="[ -f /root/.first_run ] || touch /root/.first_run";

[buildroot]
include=debian

# packages
additional_packages="bc binutils bsdextrautils bzip2 cpio diffutils file findutils g++ gcc gzip make patch perl python3 rsync sed tar unzip wget xz-utils"
additional_packages="ccache libncurses5-dev"
