CompileFlags:
  Remove:
    - -mpreferred-stack-boundary*
    - -mindirect-branch*
    - -fno-allow-store-data-races
    - -fconserve-stack
    - -mrecord-mcount
    - -fmin-function-alignment*
    - -mno-fdpic
    - -fno-ipa-sra
    - -fno-printf-return-value
    - -mfp16-format=ieee
    - -fno-reorder-functions
    - -mword-relocations
    - -mno-thumb-interwork
    - -mgeneral-regs-only
