git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
  commit:
    signOff: true
gui:
  language: "en"
os:
  editPreset: "nvim"
keybinding:
  commits:
    moveDownCommit: 'J'
    moveUpCommit: 'K'
